require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LearningModulesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # LearningModule. As you add validations to LearningModule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LearningModulesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all learning_modules as @learning_modules" do
      learning_module = LearningModule.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:learning_modules)).to eq([learning_module])
    end
  end

  describe "GET #show" do
    it "assigns the requested learning_module as @learning_module" do
      learning_module = LearningModule.create! valid_attributes
      get :show, {:id => learning_module.to_param}, valid_session
      expect(assigns(:learning_module)).to eq(learning_module)
    end
  end

  describe "GET #new" do
    it "assigns a new learning_module as @learning_module" do
      get :new, {}, valid_session
      expect(assigns(:learning_module)).to be_a_new(LearningModule)
    end
  end

  describe "GET #edit" do
    it "assigns the requested learning_module as @learning_module" do
      learning_module = LearningModule.create! valid_attributes
      get :edit, {:id => learning_module.to_param}, valid_session
      expect(assigns(:learning_module)).to eq(learning_module)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new LearningModule" do
        expect {
          post :create, {:learning_module => valid_attributes}, valid_session
        }.to change(LearningModule, :count).by(1)
      end

      it "assigns a newly created learning_module as @learning_module" do
        post :create, {:learning_module => valid_attributes}, valid_session
        expect(assigns(:learning_module)).to be_a(LearningModule)
        expect(assigns(:learning_module)).to be_persisted
      end

      it "redirects to the created learning_module" do
        post :create, {:learning_module => valid_attributes}, valid_session
        expect(response).to redirect_to(LearningModule.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved learning_module as @learning_module" do
        post :create, {:learning_module => invalid_attributes}, valid_session
        expect(assigns(:learning_module)).to be_a_new(LearningModule)
      end

      it "re-renders the 'new' template" do
        post :create, {:learning_module => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested learning_module" do
        learning_module = LearningModule.create! valid_attributes
        put :update, {:id => learning_module.to_param, :learning_module => new_attributes}, valid_session
        learning_module.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested learning_module as @learning_module" do
        learning_module = LearningModule.create! valid_attributes
        put :update, {:id => learning_module.to_param, :learning_module => valid_attributes}, valid_session
        expect(assigns(:learning_module)).to eq(learning_module)
      end

      it "redirects to the learning_module" do
        learning_module = LearningModule.create! valid_attributes
        put :update, {:id => learning_module.to_param, :learning_module => valid_attributes}, valid_session
        expect(response).to redirect_to(learning_module)
      end
    end

    context "with invalid params" do
      it "assigns the learning_module as @learning_module" do
        learning_module = LearningModule.create! valid_attributes
        put :update, {:id => learning_module.to_param, :learning_module => invalid_attributes}, valid_session
        expect(assigns(:learning_module)).to eq(learning_module)
      end

      it "re-renders the 'edit' template" do
        learning_module = LearningModule.create! valid_attributes
        put :update, {:id => learning_module.to_param, :learning_module => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested learning_module" do
      learning_module = LearningModule.create! valid_attributes
      expect {
        delete :destroy, {:id => learning_module.to_param}, valid_session
      }.to change(LearningModule, :count).by(-1)
    end

    it "redirects to the learning_modules list" do
      learning_module = LearningModule.create! valid_attributes
      delete :destroy, {:id => learning_module.to_param}, valid_session
      expect(response).to redirect_to(learning_modules_url)
    end
  end

end
